name: project_cinebeev1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
